application: colorcrumble
version: webgl-swipe
runtime: go
api_version: go1

# re-direct to index.html if no path is give
handlers:

- url: /dist/(.+)
  static_files: dist/\1
  upload: dist/(.*)

- url: /textures/(.+)
  static_files: textures/\1
  upload: textures/(.*)

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^\.idea$
- ^node_modules$
